##################################
## EternaAPI Configuration File ##
##                              ##
## Last Updated: 09.01.26       ##
##################################

# Whether to check for plugin updates when the server starts.
# Recommended: `true` - for keeping up with the latest updates.
check-for-updates: true

# Whether to keep the development tests.
# Recommended: `false` - for production servers.
keep-test-commands: true

# Whether to allow a default quest journal.
# Recommended: `true` - unless another plugin implements its own journal.
allow-quest-journal: true

# Defines the tick-rate for modules.
tick-rate:
  # Defines how ofter to update npc visibility and head rotations.
  # Default value: `2`
  npc: 2

  # Defines how often to update parkour ui.
  # Default value: `2`
  parkour: 2